config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/home' => 'static_pages#home', as: 'home'
  get '/about' => 'static_pages#about', as: 'about'
  get '/forum' => 'static_pages#forum', as: 'forum'

  delete '/favorites/:fact_id' => 'favorites#destroy', as: 'destroy_favorite'
  post '/favorites/:fact_id' => 'favorites#create', as: 'create_favorite'

  resources :facts

  resources :votes, only: [:create, :update, :destroy]

  resources :facts do
    resources :evidences
    resources :comments
  end

  devise_for :users, controllers: {   registrations: 'registrations',
                                      sessions: 'sessions',
                                      omniauth_callbacks: 'omniauth_callbacks' }

  get 'users/:id' => 'users#show', as: 'user'
  get 'users/:id/metrics' => 'users#metrics'

end

app/models/fact.rb
class Fact < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :evidences, dependent: :destroy
  has_and_belongs_to_many :favorited_users, class_name: 'User'
  has_many :votes, through: :evidences

  after_create :set_defaults

  validates :category, presence: true
  validates :body, presence: true

  require 'rmagick'
  require 'rvg/rvg'

  def set_defaults
    self.score = 0
    save
    update_image
  end

  def supporting_evidence
    evidences.where(support: true)
  end

  def refuting_evidence
    evidences.where(support: false)
  end

  def total_votes
    evidences.inject(0) do |sum, evidence|
      sum += evidence.upvotes + evidence.downvotes
    end
  end

  def controversy_score
    (score - 50).abs
  end

  def update_score
    return if total_votes == 0

    vote_sums = evidences.inject(0) do |sum, evidence|

      sum += if evidence.support
               evidence.upvotes * evidence.source.wot_factor.to_f  # upvotes on supporting evidence are good for a fact
             else
               evidence.downvotes * evidence.source.wot_factor.to_f # downvotes on refuting evidence are good for
               # a fact
             end
    end

    self.score = (vote_sums.to_f / total_votes.to_f * 100).round

    self.score = 100 if self.score > 100

    save

    update_image

    save
  end


  def update_image

    canvas = Magick::ImageList.new((Rails.env.production? ? "public/imagemagick/" : "app/assets/images/") + "base.png")

    footer_drawer = Magick::Draw.new
    footer_drawer.pointsize = 18
    footer_drawer.gravity = Magick::CenterGravity
    footer_text = "Based on #{total_votes} votes over #{evidences.count} pieces of evidence\n\nAgree? Disagree? Join the conversation and change this image!\nVisit www.truthometer.co/facts/#{id} to get started"
    footer_drawer.annotate(canvas, 645,865,0,0,footer_text) {
      self.fill = 'white'
    }

    fact_body_drawer = Magick::Draw.new
    fact_body_drawer.pointsize = 34
    fact_body_drawer.gravity = Magick::ForgetGravity
    body_text = fit_text(self.body, 375)
    fact_body_drawer.annotate(canvas, 0,0,300,150, body_text) {
      self.fill = 'black'
    }

    score_drawer = Magick::Draw.new
    score_drawer.pointsize = 50
    score_drawer.gravity = Magick::CenterGravity
    score_drawer.annotate(canvas, 290,600,0,0, self.score.to_s) {
      self.fill = 'black'
    }

    rvg = Magick::RVG.new(640, 480)
    needle = Magick::Image.read((Rails.env.production? ? "public/imagemagick/" : "app/assets/images/") + "needle.png").first
    rvg.image(needle)
    # 417

    rvg.rotate(-162, 146, 227) # 0%
    rvg.rotate( ( (self.score.to_f / 100) * 257), 146, 227)
    # rvg.rotate(257, 146, 227) # 100%
    needle = rvg.draw

    canvas.composite!(needle, 0, 0, Magick::OverCompositeOp)

    canvas.write((Rails.env.production? ? "public/imagemagick/fact_photos/" : "app/assets/images/fact_photos/") + "#{self.id}.png")

    if Rails.env.production?
      s3 = Aws::S3::Resource.new(region: 'us-east-1')
      file = "public/imagemagick/fact_photos/#{self.id}.png"
      bucket = "images.truthometer.co"
      name = File.basename file
      obj = s3.bucket(bucket).object(name)

      if obj.upload_file(file, :content_type => 'image/png')
        puts "Uploaded #{file} to bucket #{bucket}"
        self.photo_url = "http://images.truthometer.co/#{id}.png"
      else
        puts "Could not upload #{file} to bucket #{bucket}!"
      end

    end

  end

  # Checks if text fits within certain width
  def text_fit?(text, width)
    tmp_image = Magick::Image.new(width, 500)
    drawing = Magick::Draw.new
    drawing.annotate(tmp_image, 0, 0, 0, 0, text) { |txt|
      txt.gravity = Magick::NorthGravity
      txt.pointsize = 34
      txt.fill = "#ffffff"
      txt.font_family = 'helvetica'
      txt.font_weight = Magick::BoldWeight
    }
    metrics = drawing.get_multiline_type_metrics(tmp_image, text)
    (metrics.width < width)
  end

  # Adds line breaks to text to simulate word wrap
  def fit_text(text, width)
    separator = ' '
    line = ''

    if not text_fit?(text, width) and text.include? separator
      i = 0
      text.split(separator).each do |word|
        if i == 0
          tmp_line = line + word
        else
          tmp_line = line + separator + word
        end

        if text_fit?(tmp_line, width)
          unless i == 0
            line += separator
          end
          line += word
        else
          unless i == 0
            line +=  '\n'
          end
          line += word
        end
        i += 1
      end
      text = line
    end
    text
  end


end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :login_to_add_fact, only: [:create]


  # before_action :login_to_add_fact, only: [:new, :create]
  before_action :load_fact, only: [:show, :edit, :update, :destroy]
  before_action :load_categories

  helper VotesHelper

  def index

    @facts = Fact.all

    if params[:query] && params[:query].length > 1
      @facts = @facts.where('body ILIKE ?', "%#{params[:query]}%")
    end

    if params[:category]
      if params[:category].downcase == 'favorites'
        @facts = current_user.favorites
      else
        @facts = @facts.where(category: Category.where('name ILIKE ?', "%#{params[:category]}%")) unless params[:category].downcase == 'all'

      end
    end

    if params[:sort] && params[:sort].downcase != 'popular'
      case params[:sort].downcase
      when 'debated'
        @facts = @facts.sort_by(&:controversy_score) #TODO this too needs to be a db column...sorting this way is way slower
      when 'new'
        @facts = @facts.order(created_at: :desc)
      when 'false'
        @facts = @facts.order(score: :asc)
      when 'truth'
        @facts = @facts.order(score: :desc)
      end
    else
      # Default sort is popular
      @facts = @facts.sort_by(&:total_votes).reverse #TODO this needs to be a db column...sorting this way is way slower
    end

    @facts = Kaminari.paginate_array(@facts) if @facts.class == Array


    @facts = @facts.page(params[:page]).per(15)

    respond_to do |format|
      format.js {}
      format.html {}
    end

  end

  def new
    @fact = Fact.new

  end

  def show
    @fact = Fact.find(params[:id])
    @evidence = @fact.evidences.build

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @fact = Fact.create(fact_params)


    @category = @fact.category_id

    @fact.user = current_user

    if @fact.save
      flash[:notice] = 'Fact successfully created!'
      redirect_to fact_path(@fact)
    else
      flash.now[:alert] = @fact.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    @fact.update_attributes(fact_params)
    if @fact.save

      flash[:notice] = 'Fact successfully Updated!'
      redirect_to fact_path(@fact)

    else

      flash.now[:alert] = @fact.errors.full_messages.to_sentence
      render :edit

    end
  end

  def destroy
    if @fact.total_votes > 0
      redirect_to @fact, alert: 'Cannot delete fact that has votes - contact admin if you feel this is necessary'
    else
      @fact.destroy
      redirect_to facts_url notice: 'Fact Successfully Deleted'
    end
  end

  private

  def fact_params
    params.require(:fact).permit(:body, :user_id, :category_id,
                                 evidences_attributes: [:url, :support])
  end

  def load_fact
    @fact = Fact.find(params[:id])
  end

  # def login_to_add_fact
  #   unless current_user
  #     redirect_to new_user_session_path, alert: "Please login to add a Fact!"
  #   end
  # end

  def load_categories
    @categories = Category.all
  end

  def login_to_add_fact
    unless current_user
      redirect_to new_user_session_path, alert: "Please log in to create a fact!"
    end
  end
end

app/helpers/facts_helper.rb
module FactsHelper

  def favorite_button (fact)

    if !current_user || current_user.favorites.exists?(fact) == false
      link_to content_tag(:i, "", class: "fa fa-star-o unfav"),
              create_favorite_path(fact),
              method: :post,
              remote: !!current_user
    else
      link_to content_tag(:i, "", class: "fa fa-star fav"),
              destroy_favorite_path(fact),
              method: :delete,
              remote: true
    end

  end

  def query_details
    result = "<h3>Viewing <em>" +
             (params[:category] ? params[:category].capitalize : 'All') +
             "</em> facts, <em>" +
             (params[:sort] ? params[:sort].capitalize : 'Popular') +
             "</em> first"

    if params[:query] && params[:query].length > 1
      result += ", with <em>\"#{params[:query]}\"</em> in the title"
    end

    result += ":</h3>"

    result.html_safe

  end

end

app/views/facts/_evidence_form.html.erb
<div class="add-evidence-box" <%= support ? '' : 'id=refuting-box' %>>
  <p>Join the debate! Add your own evidence to <%= support ? 'support' : 'refute' %> this fact.</p>
  <%= form_for [@fact, @evidence] do |f| %>
    <div class="evidence-url-form-group">
      <%= f.url_field :url, :class => 'evidence-field', placeholder: "URL" %>
    </div>

    <%= f.hidden_field :support, value: support %>

    <div class="evidence-submit">
      <% if support %>

        <%= f.submit "Create Supporting Evidence",
                     :class => "evidence-supporting-button #{requires_login}" %>
      <% else %>

        <%= f.submit "Create Refuting Evidence",
                     :class => "evidence-refuting-button #{requires_login}" %>
      <% end %>


    </div>
  <% end %>
</div>

app/views/facts/_evidence_list.html.erb
<div class="<%= support ? 'supporting' : 'refuting' %>">
  <div class="evidence-title-box">
    <h3 class="evidence-header-text"><%= support ? 'Supporting' : 'Refuting' %> Evidence <span>(<%= support ? @fact.supporting_evidence.count : @fact.refuting_evidence.count %>)</span><a href="#add-<%= support ? 'supporting' : 'refuting' %>" class="add-evidence-anchor">+ add evidence</a></h3>
  </div>
  <ul class="evidence-list">

    <% (support ? @fact.supporting_evidence : @fact.refuting_evidence).each do |evidence| %>
      <li class="piece-of-evidence">

        <div id="vote-box-<%= evidence.id %>" class="vote-box">
          <%= render 'vote_buttons', evidence: evidence %>
        </div>
        <div class="show-evidence">

          <div class="tooltip-item source-tooltip">
            <%= "Source domain: #{evidence.source ? evidence.source.domain : 'n/a'}" %>
            <div class="tooltip">
              <p>
                <%= support ? 'Upvotes' : 'Downvotes' %> for this domain are worth <strong><%= evidence.source ? evidence.source.wot_factor.to_f.round(2) : 1.0 %></strong> of a vote. <br>
                <%= link_to 'Why?', about_path + '#weight' %>
              </p>
            </div>
          </div>

          <h4 class="evidence-title">
            <%= link_to ( evidence.title || truncate(evidence.url, length: 50) ), evidence.url, target: '_blank' %>
          </h4>

          <p class="evidence-description"><%= evidence.description || 'No site description found.' %></p>

          <p class="evidence-posting">Added by <%= link_to truncate(evidence.user.display_name, length: 8), evidence.user %> on <span><%= evidence.created_at.strftime("%b %-d, %Y") %><span></p>
          <p class="evidence-posting-mobile">By <%= link_to truncate(evidence.user.display_name, length: 15), evidence.user %> <span>on <%= evidence.created_at.strftime("%b %-d, %Y") %></span></p>

        </div>

    </li>
  <% end %>

  </ul>
</div>

app/views/facts/_fact.html.erb
<div class="fact-boxes">
  <%= react_component('FactLink', {url: "#{fact_path(:id => fact.id, :format => :json )}", pollInterval: 5000, link: fact_path(fact), title: truncate(fact.body, length: 80), truthiness: fact.score, popularity: fact.total_votes, category: fact.category.name}) %>
  <div class="fact-box-favorite"><span class="fact-box-star" id="favorite-<%= fact.id %>"><%= favorite_button(fact) %></span> <p>Posted by <%= link_to truncate(fact.user.display_name, length: 10), fact.user %> on <%= fact.created_at.strftime("%B %-d, %Y") %></p></div>
</div>

app/views/facts/_facts_index_search.html.erb
<div class="facts-index-search">
  <h4>Search Inside Selected Categories:</h4>
  <form id="form-search-index" class="search-bar" role="search" action="/facts">
    <input name="query" type="search" id="search-index" placeholder="Find a Fact" />
    <button type="submit">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
    </button>
  </form>
</div>

app/views/facts/_new_fact_form.html.erb
<div class="add-fact-box" id="new-fact-box">

  <%= form_for @fact do |f| %>

  <div>
    <%= f.label :"Take a few moments to carefully summarize it in one clear sentence (250 characters maximum) and enter it below:" %><br/>
    <%= f.text_area :body, autofocus: true, :class => 'add-fact-field', placeholder: "Enter new fact here" %>
  </div>

  <div class="field">
    <%= f.label :"select category" %>
    <%= f.select  (:category_id) do %>
    <%= content_tag(:option, '-- Category --') %>
    <%= options_from_collection_for_select(@categories, 'id', 'name',:selected => @category) %>
    <% end %>
  </div>

  <div class="add-fact-subtext">
    <p><em>Ensure that this is exactly how you would like to present your fact. You will not be able to change or delete it once someone has voted on evidence attached to this fact.</em></p>
  </div>

  <br>

  <div class="add-fact-subtext">
    <p><strong>Once submitted, you will be directed to a page dedicated to this fact where you can add evidence, vote on evidence, or copy a link to share with others!</strong></p>
  </div>

  <br>

  <div class="add-fact-submit">
    <%= f.submit "Submit New Fact",
    :class => "add-fact-button #{requires_login}"  %>
  </div>


  <% end %>

</div>

app/views/facts/_vote_buttons.html.erb
<div class="vote-buttons">
  <span class="upvote"><%= vote_button true, evidence %> <span class="numvotes"><%= evidence.upvotes %> </span></span>
  <span class="downvote"><%= vote_button false, evidence %> <span class="numvotes"><%= evidence.downvotes %> </span></span>
</div>

app/views/facts/edit.html.erb
<h1>Edit Fact</h1>
<%= render 'form' %>

app/views/facts/index.html.erb
<div class="sort-nav">

  <div class="trigger-buttons">
    <a href="#" id="category-dropdown-trigger" class="index-dropdown-trigger">Select category</a>
    <a href="#" id="sort-dropdown-trigger" class="index-dropdown-trigger">Sort by...</a>
  </div>

  <%= render 'refills/categories_filter_buttons' %>

  <%= render 'refills/sort_filter_buttons' %>

  <%= render 'facts/facts_index_search' %>

</div>

<div class="details-reset">
  <div class="query-details">
    <%= query_details %>
  </div>
  <p><%= link_to '&times;'.html_safe + 'Clear search', facts_path + '?category=all&sort=popular', remote: true , id: 'reset'%></p>
</div>

<div class="facts-container">
  <%= image_tag 'ajax-loader.gif', id: 'spinner' %>
  <ul id="facts-list" class="fact-box-wrapper">
    <%= render @facts %>
  </ul>

  <div id="index-pagination">
    <%= paginate @facts %>
  </div>
</div>

app/views/facts/index.js.erb
// Populate list of facts with what matches category/sort/search from controller
$("#facts-list").html('<%= @facts.empty? ? "No facts found - please refine your search" : (j render @facts) %>');
// Remount all react components on page that were not getting mounted post-instant search (fix empty truthiness bug)
ReactRailsUJS.mountComponents()

// Add selected class to current filter buttons and remove whatever was previously selected
$(".is-selected").toggleClass("is-selected");
$("#category-<%= params[:category] ? params[:category] : 'all' %>").toggleClass("is-selected");
$("#sort-<%= params[:sort] ? params[:sort].downcase : 'popular' %>").toggleClass("is-selected");

// Re-render pagination
$("#index-pagination").html('<%= j paginate(@facts) %>')

// Set current sort/category params
$('.category-buttons').attr('data-selected', '<%= params[:category] || "all" %>');
$('.filter-buttons').attr('data-selected', '<%= params[:sort] || "popular" %>');

// Grab current sort/category/search params
currentCategory = $('.category-buttons').attr('data-selected');
currentSort = $('.filter-buttons').attr('data-selected');
currentQuery = encodeURIComponent( $('#search-index').val() );

// Set action on category buttons so they include sort param
$('.category-buttons form').each(function(index) {
  $(this).attr('action', 'facts/?sort=' + currentSort + (currentQuery.length > 1 ? '&query=' + currentQuery : '') );
});

// Set action on sort buttons so they include category param
$('.filter-buttons form').each(function(index) {
  $(this).attr('action', 'facts/?category=' + currentCategory + (currentQuery.length > 1 ? '&query=' + currentQuery : '') );
});

// Set search results text to reflect current params
$(".query-details").html('<%= j query_details %>');

app/views/facts/new.html.erb
<!-- <div class="form-wrapper"> -->
<div>
  <h2>Passionate about a fact that you'd like the world to understand better?</h2>
  <%= render 'new_fact_form' %>
</div>

app/views/facts/show.html.erb
<div class="fact-header">
  <div id="speedo">
    <span class="speedometer"></span>
    <span class="needle"></span>
    <span id="score" class="truth-score odometer">00</span>
    <span id="actual-score" style="display:none"><%= @fact.score %></span>
  </div>

  <span class="fact-show">
      <%= @fact.body %>
  </span>
</div>

<div class="fact-favorite-text">
  <div id="favorite-<%= @fact.id %>">
    <%= favorite_button(@fact) %>
  </div>
  <span class="favorite-text-medium">Fact posted by <%= link_to truncate(@fact.user.display_name, length: 8), @fact.user %> on <%= @fact.created_at.strftime("%B %-d, %Y") %> | Category: <%= @fact.category.name %></span>
  <span class="favorite-text-mobile">By <%= link_to truncate(@fact.user.display_name, length: 8), @fact.user %> on <%= @fact.created_at.strftime("%b %-d, %Y") %> | <%= @fact.category.name %></span>
</div>

<div class="evidence">
  <%= render 'evidence_list', support: true %>
  <%= render 'evidence_list', support: false %>
</div>

<span id="add-supporting" class="anchor-span"></span>
<%= render 'evidence_form', support: true %>
<span id="add-refuting" class="anchor-span"></span>
<%= render 'evidence_form', support: false %>

<% if current_user == User.find(@fact.user_id) && @fact.total_votes == 0 %>
  <div class="delete-fact-box">
    <%= link_to "Delete This Fact",
        fact_path(@fact),
        method: :delete,
        data: { confirm:"Are you sure you want to delete this fact?" },
        class: 'delete-fact-link' %><span> (WARNING: permanently deletes this fact)</span>
  </div>
<% end  %>

<div class="permalink">
  <div class="permalink-left">
    <h2>Share this Fact</h2>
    <p>Continue the conversation! Share a link to our dynamically generated image that will automatically update its content when new evidence is created and more people vote. Think of it as a user-driven infographic.</p>
    <!-- Clipboard Target -->
    <div class="input-group">
      <label class="input-group-label" for="copy-fact-image-button">Image URL:</label>
      <input class="copy-share" id="copy-fact-image" value='<%= @fact.photo_url %>'>
      <!-- Clipboard Trigger -->
      <span class="input-group-button">
        <button id="copy-fact-image-button" class="clippy-btn" data-clipboard-target="#copy-fact-image">
            <%= image_tag "clippy.svg", alt: "Copy to clipboard", class: "clippy", width: 13 %>
        </button>
      </span>
    </div>
    <div class="input-group">
      <label class="input-group-label" for="copy-fact-iframe-button">HTML Code:</label>
      <input class="copy-share" id="copy-fact-iframe" value="<%= "<a href='#{fact_url(@fact)}'><img src='#{@fact.photo_url}'></a>" %>">
      <!-- Clipboard Trigger -->
      <span class="input-group-button">
        <button id="copy-fact-iframe-button" class="clippy-btn" data-clipboard-target="#copy-fact-iframe">
            <%= image_tag "clippy.svg", alt: "Copy to clipboard", class: "clippy", width: 13 %>
        </button>
      </span>
    </div>
  </div>
  <div id="fact-image">
    <% if Rails.env.production? %>
      <img src="<%= @fact.photo_url %>" width="224", height="168">
    <% else %>
      <%= image_tag "fact_photos/#{@fact.id.to_s}.png", width: 224, height: 168 %>
    <% end %>
  </div>
</div>

<a href="https://muut.com/i/truthometer/comments" class="muut" type="dynamic">Comments</a>
<script src="//cdn.muut.com/1/moot.min.js"></script>

<!-- TODO: Figure out how to not have this style tag in the view...-->
<style>
@-webkit-keyframes move {
    0% {
        transform:rotate(-130deg);
    }

    100% {
        transform:rotate(<%= -130 + ((@fact.score/100.0) * 260) %>deg);
    }
}</style>

<script>
  // Call clipboard.js on buttons
  (function(){
    new Clipboard('#copy-fact-image-button');
    new Clipboard('#copy-fact-iframe-button')
  })();
</script>