config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/home' => 'static_pages#home', as: 'home'
  get '/about' => 'static_pages#about', as: 'about'
  get '/forum' => 'static_pages#forum', as: 'forum'

  delete '/favorites/:fact_id' => 'favorites#destroy', as: 'destroy_favorite'
  post '/favorites/:fact_id' => 'favorites#create', as: 'create_favorite'

  resources :facts

  resources :votes, only: [:create, :update, :destroy]

  resources :facts do
    resources :evidences
    resources :comments
  end

  devise_for :users, controllers: {   registrations: 'registrations',
                                      sessions: 'sessions',
                                      omniauth_callbacks: 'omniauth_callbacks' }

  get 'users/:id' => 'users#show', as: 'user'
  get 'users/:id/metrics' => 'users#metrics'

end

app/views/refills/_categories_filter_buttons.html.erb
<div class="category-buttons" data-selected="all">
  <h4>Browse Facts by Category:</h4>
  <div class="button-group">
    <label>
      <%= button_to 'all', {}, {
          :type => 'radio',
          :name => 'category',
          :method => 'get',
          :remote => true,
          :url => facts_path } %>
      <span id="category-all" class="button-group-item<%= ' is-selected' unless params[:category] %>">All</span>
    </label>
    <% if current_user %>
      <label>
        <%= button_to 'favorites', {}, {
            :type => 'radio',
            :name => 'category',
            :method => 'get',
            :remote => true,
            :url => facts_path } %>
        <span id="category-favorites" class="button-group-item<%= ' is-selected' if params[:category] && params[:category].downcase == 'favorites' %>">My Favorites</span>
      </label>
    <% end %>
    <% @categories.each do |category| %>
        <label>
          <%= button_to category.name, {}, {
              :type => 'radio',
              :name => 'category',
              :method => 'get',
              :remote => true,
              :url => facts_path } %>
          <span id="category-<%= category.name %>" class="button-group-item<%= ' is-selected' if params[:category] && params[:category].downcase == category.name.downcase %>"><%= category.name %></span>
        </label>
    <% end %>
  </div>
</div>

app/views/refills/_favorites_flex_boxes.html.erb
<div class="stats-flex-box-wrapper">

  <div class="stats-flex-boxes">

    <% if current_user == @user %>
      <div class="stats-flex-box users-favorites">
          <h2 class="stats-flex-title">My Favorites:</h2>
          <ul>
            <% @user.favorites.each do |fact| %>
                <%= render fact %>
            <% end %>
          </ul>
      </div>
    <% end %>

  </div>

</div>

app/views/refills/_flashes.html.erb
<% if flash[:notice] %>
  <div class="flash-notice">
    <span><%= flash[:notice] %></span>
  </div>
<% elsif flash[:alert] %>
  <div class="flash-alert">
    <span><%= flash[:alert] %></span>
  </div>
<% elsif flash[:success] %>
  <div class="flash-success">
    <span><%= flash[:success] %></span>
  </div>
<% elsif flash[:error] %>
  <div class="flash-error">
    <span><%= flash[:error] %></span>
  </div>
<% end %>

app/views/refills/_flex_boxes.html.erb
<div class="flex-box-wrapper">
  <div class="flex-boxes">
    <a href="about" class="flex-box">
      <h1 class="flex-title"><i class="fa fa-file-image-o"></i> Share Dynamic Images</h1>
      <p>Our dynamically generated fact infographics will change based on community feedback! Watch the state of your facts evolve. lorem</p>
    </a>
    <a href="about" class="flex-box">
      <h1 class="flex-title"><i class="fa fa-bar-chart"></i> Evidence Based Ranking</h1>
      <p>Facts are rated based on the strength of evidence attached to them. Agree or disagree? Submit your own evidence!</p>
    </a>
    <a href="about" class="flex-box">
      <h1 class="flex-title"><i class="fa fa-university"></i> Learn Truthometer Etiquette</h1>
      <p>Our mission statement and philosophy. A set of guidelines to ensure that your truthometer experience gets a high rating.</p>
    </a>
  </div>
</div>

app/views/refills/_footer_2.html.erb
<!--<div class="wrapper-for-content-outside-of-footer">
   Uncomment this whole section for a sticky footer. The content of the page should be inside of this .wrapper-for-content-outside-of-footer
</div>-->

<footer class="footer-2" role="contentinfo">
  <div class="footer-wrapper">
    <p class="footer-paragraph">&copy; Truthometer 2016. By <a href="https://github.com/cstaikos">Chris</a>, <a href="https://github.com/pilifs">Filip</a>, <a href="https://github.com/malexanders">Matthew</a> and <a href="https://github.com/steveoneil">Steve</a>. View <a href="https://github.com/cstaikos/truthometer">source
      on github</a> / <a href="https://www.pivotaltracker.com/n/projects/1545365">Pivotal Tracker</a></p>
  </div>
</footer>

<% if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74989679-1', 'auto');
    ga('send', 'pageview');

  </script>
<% end %>

app/views/refills/_hero.html.erb
<div class="hero">
	<div class="hero-inner">
    <a href="" class="hero-logo"><%= image_tag("truthometer-logo-large-01.png", alt: 'Truthometer') %></a>
		<div class="hero-copy">
			<h1>Promoting civil discourse and debate online</h1>
      <div class="home-search-bar">
  			<%= render 'static_pages/home_page_search_bar' %>
      </div>
      <div class="home-page-or"><p>OR</p></div>
      <div class="home-add-facts">
        <h3 class="home-subheader">Add your own fact</h3>
        <p class="secondary-content">Want to share something you know to be true? Post it here and begin a public  debate validated by evidence submitted and voted on by the wider community.</p>
        <%= button_to "Add Fact", new_fact_path,
                                  method: :get,
                                  class: 'hero-button-main' + ' ' + (current_user ? '': "requires-login") %>
      </div>
      <div class="home-browse-facts">
        <h3 class="home-subheader">Browse all facts</h3>
        <p class="secondary-content">View facts on topics that are most interesting to you, searchable in many different categories. Submit or vote on evidence that supports or refutes your favorite facts.</p>
        <%= button_to "Browse Facts", facts_path, method: :get, class: 'hero-button-main' %>
      </div>

      <a href="<%= about_path %>" class="hero-footer">
        <!-- <span class="hero-about-button">ABOUT:</span> -->
        <p class="secondary-content">Find out more about Truthometer's mission statement, philosophy and site etiquette.</p>
      </a>
    </div>


	</div>
</div>

app/views/refills/_modal_authenticate.html.erb
<div class="modal">
  <input class="modal-state" id="auth-modal" type="checkbox" />
  <div class="modal-window">
    <div class="modal-inner">
      <div class="auth-error-messages">
        <!--<span>invalid email or password</span>-->
      </div>
      <label class="modal-close" for="auth-modal"></label>

      <div class="login-form">
        <h2>Log in</h2>

        <%= link_to user_omniauth_authorize_path(:google_oauth2), id: 'gpluslogin' do %>
            <span id="gptext">Google</span>
        <% end %>

        <%= link_to user_omniauth_authorize_path(:facebook), id: 'fblogin' do %>
            <span id="fbtext">Facebook</span>
        <% end %>

        <%= form_for(resource, as: resource_name, url: session_path(resource_name) ) do |f| %>

            <%= devise_error_messages! %>

            <div class="field">
              <%# f.label :email %>
              <%= f.email_field :email, autofocus: true, placeholder: "email", id: 'login-email' %>
            </div>

            <div class="field">
              <%# f.label :password %>
              <%= f.password_field :password, autocomplete: "off", placeholder: "password" %>
            </div>

            <% if devise_mapping.rememberable? -%>
                <div class="field">
                  <%= f.label :remember_me, id: "remember_me_label" %>
                  <%= f.check_box :remember_me %>
                </div>
      <% end %>

            <div class="actions">
              <%= f.submit "Log in", class: 'auth-modal-buttons' %>
            </div>

      <% end %>


        <%# link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>



        <!--<button class="googleplus">Sign in <em>w/</em> Google</button>-->
        <!--<button type="button" id="gpluslogin">-->
        <!--</button>-->


      </div>


      <div class="signup-form">
        <h2>Sign up</h2>

        <%= form_for(resource,  as: resource_name,
                     url: registration_path(resource_name),
                     html: {id: "sign_up_user"}) do |f| %>

            <%= devise_error_messages! %>


            <div class="field">
              <%# f.label :display_name %>
              <%= f.text_field :display_name, autofocus: true, placeholder: "username" %>
            </div>

            <div class="field">
              <%# f.label :email %>
              <%= f.email_field :email, placeholder: "email", id: 'signup-email' %>
            </div>

            <div class="field">
              <%# f.label :password %>
              <% if @minimum_password_length %>
                  <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %>
              <%= f.password_field :password, autocomplete: "off", placeholder: "password" %>
            </div>

            <div class="field">
              <%# f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "confirm password" %>
            </div>

            <div class="actions">
              <%= f.submit "Sign up", class: 'auth-modal-buttons' %>
            </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/refills/_navigation.html.erb
<header class="navigation nav-bg" role="banner">
  <div class="navigation-wrapper">
    <a href="<%= root_path %>" class="logo">
      <%= image_tag("truthometer-logo-large-01.png", alt: 'Truthometer', class: 'img-logo') %>
      <%= image_tag("truthometer-icon-logo.png", alt: 'Truthometer', class: 'img-logo-mobile') %>
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu"><i class="fa fa-bars"></i></a>
    <nav role="navigation">
      <div class="search-bar">
        <form role="search" action="/facts">
          <input name="query" type="search" id="search" placeholder="Search Facts" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        </form>
      </div>

      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "logout mobile-logout" )%>
        <div class="gravatar">
          <a href="<%= user_path(current_user) %>">
            <%= image_tag "http://www.gravatar.com/avatar/#{current_user.gravatar_hash}?d=identicon",
                id: "user-image-nav" %>
          </a>
        </div>
      <% else %>
        <label class="auth-modal-label" for="auth-modal">
          <div id="modal-trigger-mobile" class="modal-trigger login mobile-login">Log in / Sign up</div>
        </label>
      <% end %>

      <ul id="js-navigation-menu" class="navigation-menu show">
        <!-- cp is a helper method in application helper, returns class to highlight link if it is the currently active page -->
        <li class="nav-link <%= cp(facts_path) %>"><a href="<%= facts_path %>">Browse Facts</a></li>
        <li class="nav-link <%= cp(new_fact_path) %>"><a href="<%= new_fact_path %>"
                                class="<%= requires_login %>">Add New Fact</a></li>
        <li class="nav-link <%= cp(about_path) %>"><a href="<%= about_path %>">About</a></li>
        <li class="nav-link <%= cp(forum_path) %>"><a href="<%= forum_path %>">Forum</a></li>
      </ul>
    </nav>
    <div class="navigation-tools">
      <% if user_signed_in? %>
          <!--NOTE enter user_path when created -->
          <div id="welcome-message"><span>Welcome, <%= link_to truncate(current_user.display_name, length: 10), user_path(current_user) %></span>
            <a href="<%= user_path(current_user) %>"><%= image_tag "http://www.gravatar.com/avatar/#{current_user.gravatar_hash}?d=identicon",
                width: '34',
                height: '34',
                id: "user-image-nav"%></a>
          </div>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "logout" )%>
      <% else %>
        <label for="auth-modal">
          <div id="modal-trigger-screen" class="modal-trigger login">LOGIN / SIGNUP</div>
        </label>
      <% end %>
    </div>
  </div>
</header>
<%= render 'refills/modal_authenticate' %>

app/views/refills/_profile_flex_boxes.html.erb
<div class="profile-flex-box-wrapper">

  <div class="profile-flex-boxes">

    <div class="profile-flex-box profile-image">
      <div id="evidence-upvotes-downvotes" style="width:100%; height:200px;"></div>

      <span><%# image_tag "http://www.gravatar.com/avatar/#{@user.gravatar_hash}?d=identicon",
                id: "user-profile-image" %></span>

      <%# if current_user == @user %>
          <!--<br>-->
          <!--<p class="profile-flex-title profile-image-text"><em>No profile image?</em><br>-->
          <!--<em> <%= link_to "Click here", "https://en.gravatar.com/connect/", target: '_blank' %> to get a gravatar.</em>-->
          <!--<br>-->
          <!--<em><%= link_to "Edit Profile", edit_user_registration_path %></em>-->
          <!--</p>-->
      <%# end %>
    </div>

    <div class="profile-flex-box user-details">
      <div id="facts-upvotes-downvotes" style="width:100%; height:200px;"></div>
      <!--<h1 class="profile-flex-title">  <h1><%# @user.display_name %></h1></h1>-->

    </div>

  </div>

</div>

app/views/refills/_search_bar.html.erb
<form class="search-bar" role="search">
  <input type="search" placeholder="Start by searching for a fact:" />
  <button type="submit">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
  </button>
</form>

app/views/refills/_sort_filter_buttons.html.erb
<div class="filter-buttons" data-selected="popular">
  <h4>Sort by:</h4>
  <div class="button-group">
    <label>
      <%= button_to 'Popular', {}, {
          :method => 'get',
          :name => 'sort',
          :remote => true,
          :url => facts_path + "?sort=popular"  } %>
      <span id="sort-popular" class="button-group-item<%= ' is-selected' if !params[:sort] || params[:sort].downcase == 'popular' %>">Popular</span>
    </label>

    <label>
      <%= button_to 'Debated', {}, {
          :method => 'get',
          :name => 'sort',
          :remote => true,
          :url => facts_path + "?sort=debated" } %>
      <span id="sort-debated" class="button-group-item<%= ' is-selected' if params[:sort] && params[:sort].downcase == 'debated' %>">Debated</span>
    </label>

    <label>
      <%= button_to 'New', {}, {
          :method => 'get',
          :name => 'sort',
          :remote => true,
          :url => facts_path + "?sort=new" } %>
      <span id="sort-new" class="button-group-item<%= ' is-selected' if params[:sort] && params[:sort].downcase == 'new' %>">New</span>
    </label>

    <label>
      <%= button_to 'Truth', {}, {
          :method => 'get',
          :name => 'sort',
          :remote => true,
          :url => facts_path + "?sort=truth" } %>
          <span id="sort-truth" class="button-group-item<%= 'is-selected' if params[:sort] && params[:sort].downcase == 'truth' %>">True</span>
    </label>

    <label>
      <%= button_to 'False', {}, {
          :method => 'get',
          :name => 'sort',
          :remote => true,
          :url => facts_path + "?sort=false" } %>
      <span id="sort-false" class="button-group-item<%= ' is-selected' if params[:sort] && params[:sort].downcase == 'false' %>">False</span>
    </label>

  </div>
</div>

app/views/refills/_stats_flex_boxes.html.erb
<div class="stats-flex-box-wrapper">

  <div class="stats-flex-boxes">

    <div class="stats-flex-box users-facts">
      <h1 class="stats-flex-title">Average truthiness of submitted facts: </h1>
      <h1 class="stats-flex-score"><%= @user.facts.empty? ? 'N/A' : @user.facts.average(:score).round(2) %>%</h1>
      <h2 class="stats-flex-title-2">Total of <%= pluralize @user.facts.count, 'fact' %> posted</h2>
      <div>
        <h2 class="stats-flex-title-2">Recent facts posted:</h2>
        <ul>
          <% @user.facts.last(10).each do |fact| %>
            <li><span class="stats-flex-title-2"><%= fact.score %>%&nbsp;</span><%= link_to fact.body, fact %></li>
            <br>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="stats-flex-box users-evidence">
      <h1 class="stats-flex-title">Quality of evidence submitted: </h1>
      <h1 class="stats-flex-score"><%= @user.evidence_quality %>%</h1>
      <div>
        <h2 class="stats-flex-title-2">Recent evidence submitted:</h2>
        <ul>
          <% @user.evidences.last(10).each do |evidence| %>
            <li>
              <span class="stats-flex-title-3"><%= evidence.upvotes %> upvotes, <%= evidence.downvotes %> downvotes&nbsp;</span>
              <p><a href="<%= evidence.url %>"><%= evidence.url%></a></p>
              <p><%= evidence.support ? 'Supporting' : 'Refuting' %> evidence attached to: <%= link_to evidence.fact.body, evidence.fact %></p>
              <br>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="stats-flex-box users-votes">
      <h1 class="stats-flex-title">Total of <%= pluralize @user.votes.count, 'vote' %> cast</h1>
      <div>
        <h2 class="stats-flex-title-2">Recent Votes:</h2>
        <ul>
          <% @user.votes.last(10).each do |vote| %>
            <li>
              <p>
                <span class="stats-flex-title-3"><%= vote.upvote ? 'Upvoted' : 'Downvoted' %></span> <a href="<%= vote.evidence.url %>"><%= vote.evidence.url%></a>, <br>
                on <%= link_to vote.evidence.fact.body, vote.evidence.fact %>
              </p>
            </li>
            <br>
          <% end %>
        </ul>
      </div>
    </div>

  </div>

</div>

app/views/refills/_users_facts_flex_boxes.html.erb
<div class="stats-flex-box-wrapper">

  <div class="stats-flex-boxes">

    <% if current_user == @user %>
      <div class="stats-flex-box users-favorites">

          <h2 class="stats-flex-title">My Facts:</h2>
          <ul>
            <!--<%# @user.facts.each do |fact| %>-->
                <%= render @my_facts %>
                <%= paginate @my_facts %>
            <!--<%# end %>-->
          </ul>
      </div>
    <% end %>

  </div>

</div>